### ISSUE TITLE
Pit stop spam

### ISSUE THREAD

**Issue by Wuzzy2** [juzzlin/DustRacing2D#5]
On 4ab15830293395db4560fa9f5d9bbef733f43930, the game sometimes spams the message log with “pit stop” messages when I stop in the pit stop.

I have played around with this a bit. It seems the message appears each time my car reaches 0 km/h. If I start/stop/etc. the car on the pit stop field, I can reliably reproduce the message spam.

I suggest the game should not attempt to repair the car if it is in perfect condition.

**Comment by Wuzzy2** [comment]
Still an issue in 2.0.1.

**Comment by juzzlin** [comment]
I don't think I ever looked into this. I now fixed this by changing the horrible logic how it was intended to be and also added check for damage and tire wear. That didn't have much effect, though, as the tires start to wear immediately. Adding a bigger trigger limit for tire wear and damage would make it a bit confusing so it can be like this for now (pit stop is triggered almost always when you (re)enter the area after leaving the area).

**Comment by juzzlin** [comment]
Fixed in 7fdee13e0dd295a7f5ad8ba83b4d89171e6bacc7

**Comment by juzzlin** [comment]
Actually I had to revert this fix, because it made things sometimes worse. I should have tested it more..

**Comment by juzzlin** [comment]
This is now fixed the hard way. Thanks for pushing me on this :)

**Comment by Wuzzy2** [comment]
Unfortunately, this is still not fixed, as of 61ada1e8db21c1a38f0ec69a1dbcc94d8333caed.

I still sometimes get dozens of these messages at once when I get into the pit stop. Not always, but sometimes.

**Comment by Wuzzy2** [comment]
@juzzlin: I don't know how you tried to fix this, but:
I think one way to fix this would be to introduce a per-driver cooldown timer after using the pit stop. If a driver used the pit stop, they can't use it again for 5 seconds.

**Comment by juzzlin** [comment]
Hmm...I need to test this more then. To me it seemed to work properly. I fixed this by adding enter/exit events so that only one enter event and one exit event is received when objects goes through a trigger area. The bridge also works similarly now (but unfortunately we got this new bug with multiple bridges I still need to fix). Timeout could be one solution, but it's a bit vague to the player.
